List<String> categories = [
  'All',
  'Drone',
  'Drone Accessories',
  'Drone Parts',
  'Drone Repair',
  'Drone Training',
  'Drone Photography',
  'Drone Videography',
  'Drone Survey',
  'Drone Inspection',
  'Drone Delivery',
  'Drone Mapping',
  'Drone Inspection',
  'Drone Delivery',
  'Drone Mapping',
];
