import 'package:drone4u/models/product.dart';

List<Product> productMockDataList = [
  Product(
    name: 'Product 1',
    price: 100.00,
    discountPrice: 80.00,
    isDiscount: true,
    reviewCount: 20,
    productRating: 4.5,
  ),
  Product(
    name: 'Service 2',
    price: 100.00,
    discountPrice: 80.00,
    isDiscount: true,
    reviewCount: 20,
    productRating: 4.5,
  ),
  Product(
    name: 'Product 3',
    price: 100.00,
    discountPrice: 80.00,
    isDiscount: true,
    reviewCount: 20,
    productRating: 4.5,
  ),
  Product(
    name: 'Service 4',
    price: 100.00,
    discountPrice: 80.00,
    isDiscount: true,
    reviewCount: 20,
    productRating: 4.5,
  ),
  Product(
    name: 'Product 5',
    price: 100.00,
    discountPrice: 80.00,
    isDiscount: true,
    reviewCount: 20,
    productRating: 4.5,
  ),
  Product(
    name: 'Service 6',
    price: 100.00,
    discountPrice: 80.00,
    isDiscount: true,
    reviewCount: 20,
    productRating: 4.5,
  ),
  Product(
    name: 'Product 7',
    price: 100.00,
    discountPrice: 80.00,
    isDiscount: true,
    reviewCount: 20,
    productRating: 4.5,
  ),
  Product(
    name: 'Service 8',
    price: 100.00,
    discountPrice: 80.00,
    isDiscount: true,
    reviewCount: 20,
    productRating: 4.5,
  ),
  Product(
    name: 'Product 9',
    price: 100.00,
    discountPrice: 80.00,
    isDiscount: true,
    reviewCount: 20,
    productRating: 4.5,
  ),
  Product(
    name: 'Service 10',
    price: 100.00,
    discountPrice: 80.00,
    isDiscount: true,
    reviewCount: 20,
    productRating: 4.5,
  ),
  Product(
    name: 'Product 11',
    price: 100.00,
    discountPrice: 80.00,
    isDiscount: true,
    reviewCount: 20,
    productRating: 4.5,
  ),
];
