import 'package:drone4u/components/d4uIndex.dart';

List<D4uProductCard> salesProductCards = [
  D4uProductCard(
    sellerName: 'roger',
    productName: 'catan',
    originalPrice: 100,
    discountPrice: 80,
    isDiscount: true,
    reviewCount: '(20)',
    imagePath: 'assets/mainPageImage.jpg',
    productRating: 4.5,
    showLabel: true,
    labelText: '-20%',
  ),
  D4uProductCard(
    sellerName: 'roger',
    productName: 'catan',
    originalPrice: 100,
    discountPrice: 80,
    isDiscount: true,
    reviewCount: '(20)',
    imagePath: 'assets/d4uDrone_white.jpg',
    productRating: 4.5,
    showLabel: true,
    labelText: '-20%',
  ),
  D4uProductCard(
    sellerName: 'roger',
    productName: 'catan',
    originalPrice: 100,
    discountPrice: 80,
    isDiscount: true,
    reviewCount: '(20)',
    imagePath: 'assets/d4uDrone_road.jpg',
    productRating: 4.5,
    showLabel: true,
    labelText: '-20%',
  ),
  D4uProductCard(
    sellerName: 'roger',
    productName: 'catan',
    originalPrice: 100,
    discountPrice: 80,
    isDiscount: true,
    reviewCount: '(20)',
    imagePath: 'assets/mainPageImage.jpg',
    productRating: 4.5,
    showLabel: true,
    labelText: '-20%',
  ),
];
