import 'package:drone4u/models/product.dart';

List<Product> productMockDataList = [
  Product(
    sellerName: 'Seller A',
    name: 'Product 1',
    originalPrice: 100.00,
    discountPrice: 80.00,
    isDiscount: true,
    reviewCount: 20,
    imagePath: 'assets/mainPageImage.jpg',
    productRating: 4.5,
  ),
  Product(
    sellerName: 'Seller B',
    name: 'Service 2',
    originalPrice: 100.00,
    discountPrice: 80.00,
    isDiscount: true,
    reviewCount: 20,
    imagePath: 'assets/d4uDrone_white.jpg',
    productRating: 4.5,
  ),
  Product(
    sellerName: 'Seller C',
    name: 'Product 3',
    originalPrice: 100.00,
    discountPrice: 80.00,
    isDiscount: true,
    reviewCount: 20,
    imagePath: 'assets/d4uDrone_road.jpg',
    productRating: 4.5,
  ),
  Product(
    sellerName: 'Seller D',
    name: 'Service 4',
    originalPrice: 100.00,
    discountPrice: 80.00,
    isDiscount: true,
    reviewCount: 20,
    imagePath: 'assets/d4uDrone_road.jpg',
    productRating: 4.5,
  ),
  Product(
    sellerName: 'Seller E',
    name: 'Product 5',
    originalPrice: 100.00,
    discountPrice: 80.00,
    isDiscount: true,
    reviewCount: 20,
    imagePath: 'assets/d4uDrone_road.jpg',
    productRating: 4.5,
  ),
  Product(
    sellerName: 'Seller F',
    name: 'Service 6',
    originalPrice: 100.00,
    discountPrice: 80.00,
    isDiscount: true,
    reviewCount: 20,
    imagePath: 'assets/d4uDrone_road.jpg',
    productRating: 4.5,
  ),
  Product(
    sellerName: 'Seller G',
    name: 'Product 7',
    originalPrice: 100.00,
    discountPrice: 80.00,
    isDiscount: true,
    reviewCount: 20,
    imagePath: 'assets/d4uDrone_road.jpg',
    productRating: 4.5,
  ),
  Product(
    sellerName: 'Seller H',
    name: 'Service 8',
    originalPrice: 100.00,
    discountPrice: 80.00,
    isDiscount: true,
    reviewCount: 20,
    imagePath: 'assets/d4uDrone_road.jpg',
    productRating: 4.5,
  ),
  Product(
    sellerName: 'Seller I',
    name: 'Product 9',
    originalPrice: 100.00,
    discountPrice: 80.00,
    isDiscount: true,
    reviewCount: 20,
    imagePath: 'assets/d4uDrone_road.jpg',
    productRating: 4.5,
  ),
  Product(
    sellerName: 'Seller J',
    name: 'Service 10',
    originalPrice: 100.00,
    discountPrice: 80.00,
    isDiscount: true,
    reviewCount: 20,
    imagePath: 'assets/d4uDrone_road.jpg',
    productRating: 4.5,
  ),
  Product(
    sellerName: 'Seller K',
    name: 'Product 11',
    originalPrice: 100.00,
    discountPrice: 80.00,
    isDiscount: true,
    reviewCount: 20,
    imagePath: 'assets/d4uDrone_road.jpg',
    productRating: 4.5,
  ),
];
